namespace Vvoids.Api.Entities;

/// <summary>
/// One on One from Database Table to C# Class Object.
/// </summary>
public class Dbo
{
    public class LocationSource { public DateTime RecordChanged { get; set; } public DateTime RecordCreated { get; set; } public DateTime RecordDeleted { get; set; } public int LocationSourceID { get; set; } public string Caption { get; set; } public string Description { get; set; } }
    public class VesselLocation { public string NmeaType { get; set; } public DateTime LogDate { get; set; } public DateTime RecordChanged { get; set; } public DateTime RecordCreated { get; set; } public DateTime RecordDeleted { get; set; } public double Lat { get; set; } public double Long { get; set; } public int Course { get; set; } public int Heading { get; set; } public int LocationSourceID { get; set; } public int ProviderID { get; set; } public int Speed { get; set; } public int VesselID { get; set; } public int VesselLocationID { get; set; } public string ProviderRecordID { get; set; } }
    public class RefinedWaypointGeoDataLink { public Guid GeoDataId { get; set; } public Guid RefinedWaypointId { get; set; } }
    public class Country { public int CountryID { get; set; } public int ISOCode { get; set; } public int UNCode { get; set; } public string Capital { get; set; } public string ISOLong { get; set; } public string ISOShort { get; set; } public string LongName { get; set; } public string Name { get; set; } public string FlagIcon { get; set; } }
    public class SeaVisionEntity { public Guid CustomerId { get; set; } public Guid EntityId { get; set; } public Guid SeaVisionEntityId { get; set; } public Guid TenantId { get; set; } public string EntityName { get; set; } public string EntityType { get; set; } public string SeaVisionType { get; set; } }
    public class SeaVisionEntityTelemetry { public DateTime Timestamp { get; set; } public Guid SeaVisionEntityId { get; set; } public Guid SeaVisionEntityTelemetryId { get; set; } public string TelemetryKey { get; set; } public string TelemetryValue { get; set; } }
    public class ErrorLog { public DateTime RecordCreated { get; set; } public Guid ErrorLogID { get; set; } public Guid PersonID { get; set; } public string Detail { get; set; } public string Message { get; set; } }
    public class GeoData { public bool IsPlanned { get; set; } public DateTime Timestamp { get; set; } public decimal Latitude { get; set; } public decimal Longitude { get; set; } public float AirTemperatureHeight { get; set; } public float AirTemperatureValue { get; set; } public float IceFractionValue { get; set; } public float OceanCurrentDepth { get; set; } public float OceanCurrentDirection { get; set; } public float OceanCurrentValue { get; set; } public float SeaFloorDepthValue { get; set; } public float SeaSurfaceSalinityValue { get; set; } public float SeaSurfaceTemperatureValue { get; set; } public float StandardMeteorologyMeanSeaLevelPressure { get; set; } public float StandardMeteorologyRelativeHumidity { get; set; } public float TideDirection { get; set; } public float TideHeight { get; set; } public float TideSpeed { get; set; } public float WaveSwellDirection { get; set; } public float WaveSwellMaximumWaveHeight { get; set; } public float WaveSwellMeanPeriod { get; set; } public float WaveSwellPeakDirection { get; set; } public float WaveSwellPeakPeriod { get; set; } public float WaveSwellSignificantWaveHeight { get; set; } public float WaveSwellZeroCrossingPeriod { get; set; } public float WaveTotalSeaDirection { get; set; } public float WaveTotalSeaMaximumWaveHeight { get; set; } public float WaveTotalSeaMeanPeriod { get; set; } public float WaveTotalSeaPeakDirection { get; set; } public float WaveTotalSeaPeakPeriod { get; set; } public float WaveTotalSeaSignificantWaveHeight { get; set; } public float WaveTotalSeaZeroCrossingPeriod { get; set; } public float WaveWindSeaDirection { get; set; } public float WaveWindSeaMaximumWaveHeight { get; set; } public float WaveWindSeaMeanPeriod { get; set; } public float WaveWindSeaPeakDirection { get; set; } public float WaveWindSeaPeakPeriod { get; set; } public float WaveWindSeaSignificantWaveHeight { get; set; } public float WaveWindSeaZeroCrossingPeriod { get; set; } public Guid Id { get; set; } }
    public class RefinedWaypoint { public float Speed { get; set; } public bool IsOriginal { get; set; } public DateTime RecordChanged { get; set; } public DateTime RecordCreated { get; set; } public DateTimeOffset Timestamp { get; set; } public float Bearing { get; set; } public float Heading { get; set; } public float DistanceToEnd { get; set; } public float DistanceToNext { get; set; } public float Latitude { get; set; } public float Longitude { get; set; } public Guid PassageRouteId { get; set; } public Guid RefinedWaypointId { get; set; } public Guid VesselId { get; set; } public int Number { get; set; } }
}